server:
  port: 8762
spring:
  application:
    name: demo-provider
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql:///clouddb02?serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
eureka:
  client:
    fetch-registry: true #是否获取注册信息
    register-with-eureka: true #是否注册自己
    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
        defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: provider
    prefer-ip-address: true
info:
  app.name: microservicecloud
  company.name: www.bigtian.club
  build.artifactId: $project.artifactId$
  build.version: $project.version$
logging:
  level:
    club:
      bigtian:
        provider:
          dao: debug
mybatis-plus:
  mapper-locations: classpath:mapperxml/*.xml
